### ISSUE TITLE
Set the default selected values

### ISSUE THREAD

**Issue by ghysrc** [huajiahen/ChineseSubdivisionsPicker#2]
The picker always select the first province and the first city of the province when setup. How can I specified the province and city as default values, not always the first one.

**Comment by huajiahen** [comment]
Just set the province/city/district property of picker. Note that for ChineseSubdivisionsPickerTypeCity you must set both province and district property, and all three property must be set for ChineseSubdivisionsPickerTypeDistrict. The province/city/district name you set should match exactly with which defined in `ChineseSubdivisions.plist`.

**Comment by huajiahen** [comment]
If you have any further questions, feel free to leave a message here.
