### ISSUE TITLE
The area order in picker dismatch with plist file

### ISSUE THREAD

**Issue by maxhis** [huajiahen/ChineseSubdivisionsPicker#3]
The area list in picker has the uncommon order, and even not match the order in plist. Appreciate if you can improve it.

**Comment by huajiahen** [comment]
I had already heard some complain about this, because the order is depend on the implementation of Dictionary.keys() on different version of swift. But I did not make a decision of what order is more appropriate.

**Comment by maxhis** [comment]
We can order Dictionary.keys() like this: http://stackoverflow.com/a/25382196/1150251. Technically it can easily order by alphabet, but I think the order in your plist is more reasonable.

**Comment by huajiahen** [comment]
I had add some code and made the order in picker as same as which in plist. If you find any bug, please report here.

**Comment by maxhis** [comment]
Awesome! Works like a charm.
